name: Backend Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  LINT_JOB:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pipenv
      run: python -m pip install pipenv

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.local/share/virtualenvs
        key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
    #- name: Cache dependencies
    #  id: cache
    #  uses: actions/cache@v4
    #  with:
    #    path: ~/.local/share/virtualenvs
    #    key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
    #    restore-keys: |
    #      deps-python-

    - name: Install dependencies
      run: pipenv install --dev
  
    - name: Verify Pipfile
      run: cat Pipfile  # Verify the content of Pipfile to ensure lint script exists

    - name: Check pipenv environment
      run: pipenv --venv  # Verify that the virtual environment is created

    - name: List pipenv scripts
      run: pipenv run  # List all available scripts to ensure 'lint' is recognized

    - name: Activate virtualenv and run lint
      run: pipenv run lint
      working-directory: ./starter/backend
